language: ruby
sudo: false
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_edge.gemfile
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
